import Footer from "@/app/Components/layout/Footer";
import Header from "@/app/Components/layout/Header";
import { Analytics } from "@vercel/analytics/react";
import './globals.css';

export const metadata = {
    title: 'Perfect Party',
    description: 'Generated by create next app',
    favicon: '/assets/images/perfectPartyLogo.png',
}


export default function RootLayout({children}) {
    return (
        <>
            <head>
                <link rel='shortcut icon' href='/assets/images/PerfectPartyLogo.png' />
            </head>
            <html lang="fr">
            <body className={"bg-[#003D47]"}>
            <Header/>
            {children}
            <Analytics/>
            <Footer/>
            </body>
            </html>
        </>
    )
}
