import './globals.css'
import Header from "@/app/Components/layout/Header";
import Footer from "@/app/Components/layout/Footer";

export const metadata = {
    title: 'Perfect Party',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="fr">
        <body className={"bg-[#003D47]"}>
            <Header/>
            {children}
            <Footer/>
            </body>
        </html>
    )
}
